### ISSUE TITLE
Break with Relative mod

### ISSUE THREAD

**Issue by tbvns** [Kuuuube/Hover_Distance_Limiter#5]
This filter turn relative mod into absolute mod:
[2024-05-05 18-20-24.webm](https://github.com/Kuuuube/Hover_Distance_Limiter/assets/69420062/41d3b313-4325-4460-817e-72a744ca8f86)

**Comment by Kuuuube** [comment]
Already fixed in [0.1.3](https://github.com/Kuuuube/Hover_Distance_Limiter/releases/tag/0.1.3). If you are having trouble updating, uninstall the plugin, restart otd, install the plugin.

**Comment by tbvns** [comment]
Ok thx
